#!/bin/bash 

set -eu

SWITCH_ON_OFF="${1:-}"
if [ "${SWITCH_ON_OFF}" != "on" ] && [ "${SWITCH_ON_OFF}" != "off" ]; then
  echo "First parameter must be 'on' or 'off'"
  exit 1
fi

# E.g.: "tcp-segmentation-offload generic-segmentation-offload generic-receive-offload tx-checksumming rx"
if [ "${FEATURES:-}" == "" ]; then
  echo "Must provide list of features"
  exit 1
fi

get_interfaces() {
  local pods
  local pod_selector
  pod_selector="${1}"

  pods=$(crictl pods | awk "/${pod_selector}/ {print \$1}")
  for p in ${pods}; do
      ip a | awk -F ' |@' "/${p}/ {print \$2}"
  done
}

INTERFACES=$(get_interfaces "${POD_SELECTOR:-}")
for interface in ${INTERFACES}; do 
  for feature in ${FEATURES}; do 
    on_or_off=$(ethtool -k "${interface}" | awk "/${feature}:/ {print \$2}")
    if [ "${on_or_off}" != "${SWITCH_ON_OFF}" ]; then
      cmd="ethtool -K "${interface}" "${feature}" ${SWITCH_ON_OFF}"
      echo "Running: ${cmd}"
      ${cmd}
    fi
  done
done
